name: Bisect failures due to updating nixpkgs

on:
  push:

jobs:
  build-and-run-quick-tests:
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        package:
        - hhvm
        - hhvm_clang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: hhvm
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-experimental-features = nix-command flakes
          extra-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-public-keys = hhvm-nix-cache-1:MvKxscw16fAq6835oG8sbRgTGITb+1xGfYNhs+ee4yo=
          sandbox = false
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1544
        path: nixpkgs
        repository: NixOS/nixpkgs
        ref: 31d567846255e122846548255101980162bbf641
    - run: |
        set -ex
        cd "$GITHUB_WORKSPACE/nixpkgs"
        git bisect start \
          31d567846255e122846548255101980162bbf641 \
          91d1eb9f2a9c4e3c9d68a59f6c0cada8c63d5340
        git bisect run \
          nix build \
          --print-build-logs \
          --override-input "$GITHUB_WORKSPACE/nixpkgs" github:NixOS/nixpkgs \
          "git+file://$GITHUB_WORKSPACE/hhvm?submodules=1&shallow=1#${{matrix.package}}"
