name: Nix CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{matrix.os}}
    continue-on-error: ${{ matrix.os == 'macos-latest' }}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-experimental-features = nix-command flakes
          extra-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-public-keys = hhvm-nix-cache-1:MvKxscw16fAq6835oG8sbRgTGITb+1xGfYNhs+ee4yo=
    - run: nix-build --no-sandbox
    - run: nix profile install --print-build-logs --no-sandbox "git+file://$(pwd)?submodules=1&shallow=1"
    - run: nix flake check --print-build-logs --no-sandbox "git+file://$(pwd)?submodules=1&shallow=1"
    - run: hhvm --version
    - run: nix flake check --print-build-logs --no-sandbox "git+file://$(pwd)?submodules=1&shallow=1"
    - name: Build the deb package
      if: runner.os == 'Linux'
      run: nix bundle --print-build-logs --bundler "git+file://$(pwd)?submodules=1&shallow=1#deb" "git+file://$(pwd)?submodules=1&shallow=1"
    - name: Show the deb package's information
      if: runner.os == 'Linux'
      run: dpkg-deb --info bundle.deb
    - name: Show the deb package's content
      if: runner.os == 'Linux'
      run: dpkg-deb --contents bundle.deb
    - name: Save the deb package as build artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: bundle.deb
        path: bundle.deb
    - name: Build the rpm package
      if: runner.os == 'Linux'
      run: nix bundle --print-build-logs --bundler "git+file://$(pwd)?submodules=1&shallow=1#rpm" "git+file://$(pwd)?submodules=1&shallow=1"
    - name: Show the rpm package's information
      if: runner.os == 'Linux'
      run: rpm --query --info --package bundle.rpm
    - name: Show the rpm package's content
      if: runner.os == 'Linux'
      run: rpm --query --list --package bundle.rpm
    - name: Save the rpm package as build artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: bundle.rpm
        path: bundle.rpm
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      if: github.event_name != 'pull_request'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Sign Nix binaries with a private key downloaded from AWS Secrets Manager
      if: steps.configure-aws-credentials.outcome == 'success'
      run: nix store sign --recursive --key-file <(aws secretsmanager get-secret-value --secret-id hhvm-nix-cache-1 --query SecretString --output text) --print-build-logs --no-sandbox "git+file://$(pwd)?submodules=1&shallow=1"
    - name: Upload Nix binaries to the binary cache server on S3
      if: steps.configure-aws-credentials.outcome == 'success'
      run: nix copy --to 's3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com' --print-build-logs --no-sandbox "git+file://$(pwd)?submodules=1&shallow=1"
  upload-deb:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Download the bundle.deb from build-and-test job
      uses: actions/download-artifact@v2
      with:
        name: bundle.deb
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-experimental-features = nix-command flakes
          extra-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-public-keys = hhvm-nix-cache-1:MvKxscw16fAq6835oG8sbRgTGITb+1xGfYNhs+ee4yo=
    - run: nix profile install nixpkgs#s3fs
    - run: dpkg --info bundle.deb
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Decrypt the GPG key
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -o pipefail
        aws kms decrypt \
            --ciphertext-blob "fileb://$PWD/gpg-key.kms-ciphertext" \
            --query Plaintext \
            --output text |
        base64 --decode |
        gpg --import
    - name: Upload the deb package
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -e
        sudo mkdir /mnt/hhvm-downloads
        sudo chown "$USER" /mnt/hhvm-downloads
        AWSACCESSKEYID="$AWS_ACCESS_KEY_ID"" \
        AWSSECRETACCESSKEY="$AWS_SECRET_ACCESS_KEY"" \
        AWSSESSIONTOKEN="$AWS_SESSION_TOKEN"" \
        s3fs -o use_session_token hhvm-downloads /mnt/hhvm-downloads
        mkdir -p /mnt/hhvm-downloads/test-universal-packages
        echo 'Hello, World!' > /mnt/hhvm-downloads/test-universal-packages/hello

